export const CATEGORIES = [
  {
    id: "eliquid",
    label: "سالت نیکوتین",
    color: "#2F86FF",
  },
  {
    id: "device",
    label: "پاد دائمی",
    color: "#FF8A3D",
  },
  {
    id: "pod",
    label: "کارتریج",
    color: "#22E5C9",
  },
  {
    id: "accessory",
    label: "پاد یکبارمصرف",
    color: "#C6FF3D",
  },
];

export const PRODUCTS = [
  {
    id: "p1",
    name: "Caliburn Tenet Koko",
    category: "device",
    brand: "Caliburn",
    price: 2000000,
    discount: 16,
    rating: 4.8,
    reviewsCount: 132,
    color: "#2F86FF",
    badge: "پرفروش",
    available: true,
    images: ["/pod-koko-tenet.jpg"],
    description: "محصول تستی برای نمایش کارت محصول.",
    specs: [
      { k: "نوع", v: "محصول تستی" },
      { k: "رنگ", v: "مشکی" },
      { k: "وضعیت", v: "موجود" },
    ],
    reviews: [],
  },

  {
    id: "p2",
    name: "محصول تستی شماره ۲",
    category: "accessory",
    brand: "PurpleFog",
    price: 1349000,
    discount: 11,
    rating: 4.6,
    reviewsCount: 88,
    color: "#FF8A3D",
    badge: "جدید",
    available: true,
    images: ["/maxgo-22000.jpg"],
    description: "محصول تستی برای بررسی ظاهر فروشگاه.",
    specs: [
      { k: "نوع", v: "اکسسوری" },
      { k: "رنگ", v: "نارنجی" },
    ],
    reviews: [],
  },

  {
    id: "p3",
    name: "محصول تستی شماره ۳",
    category: "eliquid",
    brand: "Oxva",
    price: 1399000,
    discount: 0,
    rating: 4.9,
    reviewsCount: 210,
    color: "#22E5C9",
    badge: "محبوب",
    available: true,
    images: ["/salt-oxva.jpg"],
    description: "محصول تستی برای بررسی کارت محصولات.",
    specs: [
      { k: "نوع", v: "محصول تستی" },
      { k: "وضعیت", v: "موجود" },
    ],
    reviews: [],
  },

  {
    id: "p4",
    name: "محصول تستی شماره ۴",
    category: "pod",
    brand: "Nova",
    price: 180000,
    discount: 0,
    rating: 4.5,
    reviewsCount: 64,
    color: "#22E5C9",
    badge: "",
    available: true,
    images: ["/pod-koko-tenet2.jpg"],
    description: "محصول تستی برای نمایش کارت.",
    specs: [
      { k: "نوع", v: "محصول تستی" },
      { k: "تعداد", v: "۳ عدد" },
    ],
    reviews: [],
  },

  {
    id: "p5",
    name: "محصول تستی شماره ۵",
    category: "eliquid",
    brand: "CloudBerry",
    price: 460000,
    discount: 20,
    rating: 4.7,
    reviewsCount: 156,
    color: "#C6FF3D",
    badge: "تخفیف ویژه",
    available: true,
    images: ["/salt-oxva.jpg"],
    description: "محصول تستی برای بررسی تخفیف و قیمت.",
    specs: [
      { k: "نوع", v: "محصول تستی" },
      { k: "تخفیف", v: "۲۰٪" },
    ],
    reviews: [],
  },

  {
    id: "p6",
    name: "محصول تستی شماره ۶",
    category: "accessory",
    brand: "CarryOn",
    price: 210000,
    discount: 0,
    rating: 4.3,
    reviewsCount: 40,
    color: "#C6FF3D",
    badge: "",
    available: false,
    images: ["/maxgo-22000.jpg"],
    description: "محصول تستی شماره شش.",
    specs: [
      { k: "نوع", v: "اکسسوری" },
      { k: "وضعیت", v: "ناموجود" },
    ],
    reviews: [],
  },

  {
    id: "p7",
    name: "محصول تستی شماره ۷",
    category: "device",
    brand: "VaporLab",
    price: 1750000,
    discount: 8,
    rating: 4.7,
    reviewsCount: 72,
    color: "#2F86FF",
    badge: "جدید",
    available: true,
    images: ["/pod-koko-tenet.jpg"],
    description: "محصول تستی شماره هفت.",
    specs: [
      { k: "نوع", v: "دستگاه" },
      { k: "رنگ", v: "آبی" },
    ],
    reviews: [],
  },

  {
    id: "p8",
    name: "محصول تستی شماره ۸",
    category: "pod",
    brand: "Nova",
    price: 260000,
    discount: 5,
    rating: 4.4,
    reviewsCount: 51,
    color: "#22E5C9",
    badge: "",
    available: true,
    images: ["/pod-koko-tenet2.jpg"],
    description: "محصول تستی شماره هشت.",
    specs: [
      { k: "نوع", v: "کارتریج" },
      { k: "تعداد", v: "۲ عدد" },
    ],
    reviews: [],
  },

  {
    id: "p9",
    name: "محصول تستی شماره ۹",
    category: "accessory",
    brand: "CarryOn",
    price: 320000,
    discount: 12,
    rating: 4.6,
    reviewsCount: 93,
    color: "#FF8A3D",
    badge: "پرفروش",
    available: true,
    images: ["/maxgo-22000.jpg"],
    description: "محصول تستی شماره نه.",
    specs: [
      { k: "نوع", v: "اکسسوری" },
      { k: "رنگ", v: "مشکی" },
    ],
    reviews: [],
  },

  {
    id: "p10",
    name: "محصول تستی شماره ۱۰",
    category: "device",
    brand: "VaporLab",
    price: 2250000,
    discount: 15,
    rating: 4.8,
    reviewsCount: 117,
    color: "#2F86FF",
    badge: "ویژه",
    available: true,
    images: ["/pod-koko-tenet.jpg"],
    description: "محصول تستی شماره ده.",
    specs: [
      { k: "نوع", v: "دستگاه" },
      { k: "وضعیت", v: "موجود" },
    ],
    reviews: [],
  },

  {
    id: "p11",
    name: "محصول تستی شماره ۱۱",
    category: "eliquid",
    brand: "CloudBerry",
    price: 520000,
    discount: 10,
    rating: 4.5,
    reviewsCount: 61,
    color: "#C6FF3D",
    badge: "",
    available: true,
    images: ["/salt-oxva.jpg"],
    description: "محصول تستی شماره یازده.",
    specs: [
      { k: "نوع", v: "محصول تستی" },
      { k: "حجم", v: "۳۰ میلی‌لیتر" },
    ],
    reviews: [],
  },

  {
    id: "p12",
    name: "محصول تستی شماره ۱۲",
    category: "pod",
    brand: "Nova",
    price: 295000,
    discount: 0,
    rating: 4.3,
    reviewsCount: 42,
    color: "#22E5C9",
    badge: "",
    available: false,
    images: ["/pod-koko-tenet2.jpg"],
    description: "محصول تستی شماره دوازده.",
    specs: [
      { k: "نوع", v: "کارتریج" },
      { k: "وضعیت", v: "ناموجود" },
    ],
    reviews: [],
  },

  {
    id: "p13",
    name: "محصول تستی شماره ۱۳",
    category: "accessory",
    brand: "CarryOn",
    price: 390000,
    discount: 18,
    rating: 4.7,
    reviewsCount: 84,
    color: "#C6FF3D",
    badge: "تخفیف",
    available: true,
    images: ["/maxgo-22000.jpg"],
    description: "محصول تستی شماره سیزده.",
    specs: [
      { k: "نوع", v: "اکسسوری" },
      { k: "رنگ", v: "سبز" },
    ],
    reviews: [],
  },

  {
    id: "p14",
    name: "محصول تستی شماره ۱۴",
    category: "device",
    brand: "Caliburn",
    price: 1890000,
    discount: 7,
    rating: 4.6,
    reviewsCount: 73,
    color: "#2F86FF",
    badge: "",
    available: true,
    images: ["/pod-koko-tenet.jpg"],
    description: "محصول تستی شماره چهارده.",
    specs: [
      { k: "نوع", v: "دستگاه" },
      { k: "رنگ", v: "آبی" },
    ],
    reviews: [],
  },

  {
    id: "p15",
    name: "محصول تستی شماره ۱۵",
    category: "eliquid",
    brand: "CloudBerry",
    price: 490000,
    discount: 5,
    rating: 4.4,
    reviewsCount: 58,
    color: "#C6FF3D",
    badge: "جدید",
    available: false,
    images: ["/salt-oxva.jpg"],
    description: "محصول تستی شماره پانزده.",
    specs: [
      { k: "نوع", v: "محصول تستی" },
      { k: "حجم", v: "۳۰ میلی‌لیتر" },
      { k: "وضعیت", v: "ناموجود" },
    ],
    reviews: [],
  },

  {
    id: "p16",
    name: "محصول تستی شماره ۱۶",
    category: "pod",
    brand: "Nova",
    price: 230000,
    discount: 0,
    rating: 4.2,
    reviewsCount: 37,
    color: "#22E5C9",
    badge: "",
    available: true,
    images: ["/pod-koko-tenet2.jpg"],
    description: "محصول تستی شماره شانزده.",
    specs: [
      { k: "نوع", v: "کارتریج" },
      { k: "تعداد", v: "۳ عدد" },
    ],
    reviews: [],
  },

  {
    id: "p17",
    name: "محصول تستی شماره ۱۷",
    category: "accessory",
    brand: "CarryOn",
    price: 280000,
    discount: 9,
    rating: 4.5,
    reviewsCount: 49,
    color: "#FF8A3D",
    badge: "",
    available: true,
    images: ["/maxgo-22000.jpg"],
    description: "محصول تستی شماره هفده.",
    specs: [
      { k: "نوع", v: "اکسسوری" },
      { k: "وضعیت", v: "موجود" },
    ],
    reviews: [],
  },

  {
    id: "p18",
    name: "محصول تستی شماره ۱۸",
    category: "device",
    brand: "VaporLab",
    price: 2100000,
    discount: 13,
    rating: 4.8,
    reviewsCount: 126,
    color: "#2F86FF",
    badge: "پرفروش",
    available: true,
    images: ["/pod-koko-tenet.jpg"],
    description: "محصول تستی شماره هجده.",
    specs: [
      { k: "نوع", v: "دستگاه" },
      { k: "وضعیت", v: "موجود" },
    ],
    reviews: [],
  },

  {
    id: "p19",
    name: "محصول تستی شماره ۱۹",
    category: "eliquid",
    brand: "Oxva",
    price: 610000,
    discount: 15,
    rating: 4.7,
    reviewsCount: 91,
    color: "#22E5C9",
    badge: "ویژه",
    available: true,
    images: ["/salt-oxva.jpg"],
    description: "محصول تستی شماره نوزده.",
    specs: [
      { k: "نوع", v: "محصول تستی" },
      { k: "حجم", v: "۳۰ میلی‌لیتر" },
    ],
    reviews: [],
  },

  {
    id: "p20",
    name: "محصول تستی شماره ۲۰",
    category: "pod",
    brand: "Nova",
    price: 350000,
    discount: 10,
    rating: 4.6,
    reviewsCount: 68,
    color: "#22E5C9",
    badge: "جدید",
    available: false,
    images: ["/pod-koko-tenet2.jpg"],
    description: "محصول تستی شماره بیست.",
    specs: [
      { k: "نوع", v: "کارتریج" },
      { k: "تعداد", v: "۳ عدد" },
      { k: "وضعیت", v: "ناموجود" },
    ],
    reviews: [],
  },

  {
    id: "p21",
    name: "محصول تستی شماره ۲۱",
    category: "accessory",
    brand: "CarryOn",
    price: 420000,
    discount: 6,
    rating: 4.3,
    reviewsCount: 35,
    color: "#C6FF3D",
    badge: "",
    available: true,
    images: ["/maxgo-22000.jpg"],
    description: "محصول تستی شماره بیست و یک.",
    specs: [
      { k: "نوع", v: "اکسسوری" },
      { k: "جنس", v: "مقاوم" },
    ],
    reviews: [],
  },

  {
    id: "p22",
    name: "محصول تستی شماره ۲۲",
    category: "device",
    brand: "Caliburn",
    price: 2450000,
    discount: 20,
    rating: 4.9,
    reviewsCount: 154,
    color: "#2F86FF",
    badge: "تخفیف ویژه",
    available: true,
    images: ["/pod-koko-tenet.jpg"],
    description: "محصول تستی شماره بیست و دو.",
    specs: [
      { k: "نوع", v: "دستگاه" },
      { k: "وضعیت", v: "موجود" },
    ],
    reviews: [],
  },

  {
    id: "p23",
    name: "محصول تستی شماره ۲۳",
    category: "eliquid",
    brand: "CloudBerry",
    price: 550000,
    discount: 0,
    rating: 4.5,
    reviewsCount: 44,
    color: "#C6FF3D",
    badge: "",
    available: true,
    images: ["/salt-oxva.jpg"],
    description: "محصول تستی شماره بیست و سه.",
    specs: [
      { k: "نوع", v: "محصول تستی" },
      { k: "وضعیت", v: "موجود" },
    ],
    reviews: [],
  },

  {
    id: "p24",
    name: "محصول تستی شماره ۲۴",
    category: "pod",
    brand: "Nova",
    price: 275000,
    discount: 12,
    rating: 4.4,
    reviewsCount: 56,
    color: "#22E5C9",
    badge: "",
    available: false,
    images: ["/pod-koko-tenet2.jpg"],
    description: "محصول تستی شماره بیست و چهار.",
    specs: [
      { k: "نوع", v: "کارتریج" },
      { k: "تعداد", v: "۲ عدد" },
      { k: "وضعیت", v: "ناموجود" },
    ],
    reviews: [],
  },

  {
    id: "p25",
    name: "محصول تستی شماره ۲۵",
    category: "accessory",
    brand: "CarryOn",
    price: 310000,
    discount: 8,
    rating: 4.7,
    reviewsCount: 76,
    color: "#FF8A3D",
    badge: "پرفروش",
    available: true,
    images: ["/maxgo-22000.jpg"],
    description: "محصول تستی شماره بیست و پنج.",
    specs: [
      { k: "نوع", v: "اکسسوری" },
      { k: "رنگ", v: "مشکی" },
    ],
    reviews: [],
  },

  {
    id: "p26",
    name: "محصول تستی شماره ۲۶",
    category: "device",
    brand: "VaporLab",
    price: 1980000,
    discount: 10,
    rating: 4.6,
    reviewsCount: 83,
    color: "#2F86FF",
    badge: "جدید",
    available: true,
    images: ["/pod-koko-tenet.jpg"],
    description: "محصول تستی شماره بیست و شش.",
    specs: [
      { k: "نوع", v: "دستگاه" },
      { k: "رنگ", v: "مشکی" },
    ],
    reviews: [],
  },

  {
    id: "p27",
    name: "محصول تستی شماره ۲۷",
    category: "eliquid",
    brand: "Oxva",
    price: 680000,
    discount: 17,
    rating: 4.8,
    reviewsCount: 102,
    color: "#22E5C9",
    badge: "ویژه",
    available: true,
    images: ["/salt-oxva.jpg"],
    description: "محصول تستی شماره بیست و هفت.",
    specs: [
      { k: "نوع", v: "محصول تستی" },
      { k: "حجم", v: "۳۰ میلی‌لیتر" },
    ],
    reviews: [],
  },

  {
    id: "p28",
    name: "محصول تستی شماره ۲۸",
    category: "pod",
    brand: "Nova",
    price: 315000,
    discount: 5,
    rating: 4.3,
    reviewsCount: 39,
    color: "#22E5C9",
    badge: "",
    available: false,
    images: ["/pod-koko-tenet2.jpg"],
    description: "محصول تستی شماره بیست و هشت.",
    specs: [
      { k: "نوع", v: "کارتریج" },
      { k: "تعداد", v: "۳ عدد" },
      { k: "وضعیت", v: "ناموجود" },
    ],
    reviews: [],
  },

  {
    id: "p29",
    name: "محصول تستی شماره ۲۹",
    category: "accessory",
    brand: "CarryOn",
    price: 450000,
    discount: 14,
    rating: 4.6,
    reviewsCount: 67,
    color: "#C6FF3D",
    badge: "تخفیف",
    available: true,
    images: ["/maxgo-22000.jpg"],
    description: "محصول تستی شماره بیست و نه.",
    specs: [
      { k: "نوع", v: "اکسسوری" },
      { k: "جنس", v: "مقاوم" },
    ],
    reviews: [],
  },

  {
    id: "p30",
    name: "محصول تستی شماره ۳۰",
    category: "device",
    brand: "Caliburn",
    price: 2300000,
    discount: 9,
    rating: 4.9,
    reviewsCount: 188,
    color: "#2F86FF",
    badge: "پرفروش",
    available: true,
    images: ["/pod-koko-tenet.jpg"],
    description: "محصول تستی شماره سی.",
    specs: [
      { k: "نوع", v: "دستگاه" },
      { k: "وضعیت", v: "موجود" },
    ],
    reviews: [],
  },

  {
    id: "p31",
    name: "محصول تستی شماره ۳۱",
    category: "eliquid",
    brand: "CloudBerry",
    price: 580000,
    discount: 11,
    rating: 4.4,
    reviewsCount: 48,
    color: "#C6FF3D",
    badge: "",
    available: true,
    images: ["/salt-oxva.jpg"],
    description: "محصول تستی شماره سی و یک.",
    specs: [
      { k: "نوع", v: "محصول تستی" },
      { k: "وضعیت", v: "موجود" },
    ],
    reviews: [],
  },

  {
    id: "p32",
    name: "محصول تستی شماره ۳۲",
    category: "pod",
    brand: "Nova",
    price: 290000,
    discount: 0,
    rating: 4.5,
    reviewsCount: 55,
    color: "#22E5C9",
    badge: "جدید",
    available: true,
    images: ["/pod-koko-tenet2.jpg"],
    description: "محصول تستی شماره سی و دو.",
    specs: [
      { k: "نوع", v: "کارتریج" },
      { k: "تعداد", v: "۲ عدد" },
    ],
    reviews: [],
  },

  {
    id: "p33",
    name: "محصول تستی شماره ۳۳",
    category: "accessory",
    brand: "CarryOn",
    price: 370000,
    discount: 7,
    rating: 4.2,
    reviewsCount: 31,
    color: "#FF8A3D",
    badge: "",
    available: false,
    images: ["/maxgo-22000.jpg"],
    description: "محصول تستی شماره سی و سه.",
    specs: [
      { k: "نوع", v: "اکسسوری" },
      { k: "رنگ", v: "نارنجی" },
      { k: "وضعیت", v: "ناموجود" },
    ],
    reviews: [],
  },

  {
    id: "p34",
    name: "محصول تستی شماره ۳۴",
    category: "device",
    brand: "VaporLab",
    price: 2150000,
    discount: 18,
    rating: 4.7,
    reviewsCount: 119,
    color: "#2F86FF",
    badge: "تخفیف ویژه",
    available: true,
    images: ["/pod-koko-tenet.jpg"],
    description: "محصول تستی شماره سی و چهار.",
    specs: [
      { k: "نوع", v: "دستگاه" },
      { k: "وضعیت", v: "موجود" },
    ],
    reviews: [],
  },

  {
    id: "p35",
    name: "محصول تستی شماره ۳۵",
    category: "eliquid",
    brand: "Oxva",
    price: 625000,
    discount: 6,
    rating: 4.6,
    reviewsCount: 71,
    color: "#22E5C9",
    badge: "",
    available: true,
    images: ["/salt-oxva.jpg"],
    description: "محصول تستی شماره سی و پنج.",
    specs: [
      { k: "نوع", v: "محصول تستی" },
      { k: "حجم", v: "۳۰ میلی‌لیتر" },
    ],
    reviews: [],
  },

  {
    id: "p36",
    name: "محصول تستی شماره ۳۶",
    category: "pod",
    brand: "Nova",
    price: 340000,
    discount: 13,
    rating: 4.8,
    reviewsCount: 89,
    color: "#22E5C9",
    badge: "محبوب",
    available: true,
    images: ["/pod-koko-tenet2.jpg"],
    description: "محصول تستی شماره سی و شش.",
    specs: [
      { k: "نوع", v: "کارتریج" },
      { k: "تعداد", v: "۳ عدد" },
    ],
    reviews: [],
  },

  {
    id: "p37",
    name: "محصول تستی شماره ۳۷",
    category: "accessory",
    brand: "CarryOn",
    price: 480000,
    discount: 10,
    rating: 4.5,
    reviewsCount: 62,
    color: "#C6FF3D",
    badge: "جدید",
    available: true,
    images: ["/maxgo-22000.jpg"],
    description: "محصول تستی شماره سی و هفت.",
    specs: [
      { k: "نوع", v: "اکسسوری" },
      { k: "جنس", v: "مقاوم" },
    ],
    reviews: [],
  },

  {
    id: "p38",
    name: "محصول تستی شماره ۳۸",
    category: "device",
    brand: "Caliburn",
    price: 2600000,
    discount: 12,
    rating: 4.9,
    reviewsCount: 143,
    color: "#2F86FF",
    badge: "پرفروش",
    available: true,
    images: ["/pod-koko-tenet.jpg"],
    description: "محصول تستی شماره سی و هشت.",
    specs: [
      { k: "نوع", v: "دستگاه" },
      { k: "وضعیت", v: "موجود" },
    ],
    reviews: [],
  },

  {
    id: "p39",
    name: "محصول تستی شماره ۳۹",
    category: "eliquid",
    brand: "CloudBerry",
    price: 640000,
    discount: 16,
    rating: 4.7,
    reviewsCount: 96,
    color: "#C6FF3D",
    badge: "تخفیف",
    available: false,
    images: ["/salt-oxva.jpg"],
    description: "محصول تستی شماره سی و نه.",
    specs: [
      { k: "نوع", v: "محصول تستی" },
      { k: "حجم", v: "۳۰ میلی‌لیتر" },
      { k: "وضعیت", v: "ناموجود" },
    ],
    reviews: [],
  },

  {
    id: "p40",
    name: "محصول تستی شماره ۴۰",
    category: "pod",
    brand: "Nova",
    price: 360000,
    discount: 20,
    rating: 4.8,
    reviewsCount: 112,
    color: "#22E5C9",
    badge: "تخفیف ویژه",
    available: true,
    images: ["/pod-koko-tenet2.jpg"],
    description: "محصول تستی شماره چهل.",
    specs: [
      { k: "نوع", v: "کارتریج" },
      { k: "تعداد", v: "۳ عدد" },
    ],
    reviews: [],
  },
];

export const money = (n) =>
  n.toLocaleString("fa-IR") + " تومان";

export const discountedPrice = (p) =>
  Math.round(p.price * (1 - p.discount / 100));

export function getProductById(id) {
  return PRODUCTS.find((p) => p.id === id) || null;
}

export function getRelated(product, limit = 4) {
  return PRODUCTS
    .filter(
      (p) =>
        p.category === product.category &&
        p.id !== product.id
    )
    .slice(0, limit);
}
