// لیست همه‌ی عکس‌های سایت که از پنل ادمین قابل تغییرن
// هر محصول یه فایل عکس مجزا داره (توی public/products/) که مستقل از بقیه قابل تغییره
// اگه محصول جدیدی به lib/data.js اضافه کردی، یادت نره یه آیتم متناظر اینجا هم اضافه کنی

export const IMAGE_SLOTS = [
  { group: "هویت سایت", path: "/digihaze.svg", label: "لوگوی سایت" },

  { group: "اسلایدر صفحه اصلی", path: "/slider.jpg", label: "اسلاید شماره ۱" },
  { group: "اسلایدر صفحه اصلی", path: "/slider2+.jpg", label: "اسلاید شماره ۲" },
  { group: "اسلایدر صفحه اصلی", path: "/slider3.jpg", label: "اسلاید شماره ۳" },

  { group: "دسته‌بندی محصولات (صفحه اصلی)", path: "/category-pod-system.jpg", label: "کارت پاد سیستم" },
  { group: "دسته‌بندی محصولات (صفحه اصلی)", path: "/category-salt-nicotine.jpg", label: "کارت سالت نیکوتین" },
  { group: "دسته‌بندی محصولات (صفحه اصلی)", path: "/category-disposable-pod.jpg", label: "کارت پاد یکبار مصرف" },
  { group: "دسته‌بندی محصولات (صفحه اصلی)", path: "/category-cartridge.jpg", label: "کارت کارتریج" },

  { group: "بنر عریض دسته‌بندی (صفحه فروشگاه)", path: "/category-banner-pod-system.jpg", label: "بنر پاد سیستم" },
  { group: "بنر عریض دسته‌بندی (صفحه فروشگاه)", path: "/category-banner-salt-nicotine.jpg", label: "بنر سالت نیکوتین" },
  { group: "بنر عریض دسته‌بندی (صفحه فروشگاه)", path: "/category-banner-disposable-pod.jpg", label: "بنر پاد یکبار مصرف" },
  { group: "بنر عریض دسته‌بندی (صفحه فروشگاه)", path: "/category-banner-cartridge.jpg", label: "بنر کارتریج" },

  { group: "بنر تخفیف هفتگی (صفحه اصلی)", path: "/discount-banner.jpg", label: "بنر تخفیف" },

  { group: "عکس محصولات", path: "/products/p1.jpg", label: "Caliburn Tenet Koko" },
  { group: "عکس محصولات", path: "/products/p2.jpg", label: "محصول تستی شماره ۲" },
  { group: "عکس محصولات", path: "/products/p3.jpg", label: "محصول تستی شماره ۳" },
  { group: "عکس محصولات", path: "/products/p4.jpg", label: "محصول تستی شماره ۴" },
  { group: "عکس محصولات", path: "/products/p5.jpg", label: "محصول تستی شماره ۵" },
  { group: "عکس محصولات", path: "/products/p6.jpg", label: "محصول تستی شماره ۶" },
  { group: "عکس محصولات", path: "/products/p7.jpg", label: "محصول تستی شماره ۷" },
  { group: "عکس محصولات", path: "/products/p8.jpg", label: "محصول تستی شماره ۸" },
  { group: "عکس محصولات", path: "/products/p9.jpg", label: "محصول تستی شماره ۹" },
  { group: "عکس محصولات", path: "/products/p10.jpg", label: "محصول تستی شماره ۱۰" },
  { group: "عکس محصولات", path: "/products/p11.jpg", label: "محصول تستی شماره ۱۱" },
  { group: "عکس محصولات", path: "/products/p12.jpg", label: "محصول تستی شماره ۱۲" },
  { group: "عکس محصولات", path: "/products/p13.jpg", label: "محصول تستی شماره ۱۳" },
  { group: "عکس محصولات", path: "/products/p14.jpg", label: "محصول تستی شماره ۱۴" },
  { group: "عکس محصولات", path: "/products/p15.jpg", label: "محصول تستی شماره ۱۵" },
  { group: "عکس محصولات", path: "/products/p16.jpg", label: "محصول تستی شماره ۱۶" },
  { group: "عکس محصولات", path: "/products/p17.jpg", label: "محصول تستی شماره ۱۷" },
  { group: "عکس محصولات", path: "/products/p18.jpg", label: "محصول تستی شماره ۱۸" },
  { group: "عکس محصولات", path: "/products/p19.jpg", label: "محصول تستی شماره ۱۹" },
  { group: "عکس محصولات", path: "/products/p20.jpg", label: "محصول تستی شماره ۲۰" },
  { group: "عکس محصولات", path: "/products/p21.jpg", label: "محصول تستی شماره ۲۱" },
  { group: "عکس محصولات", path: "/products/p22.jpg", label: "محصول تستی شماره ۲۲" },
  { group: "عکس محصولات", path: "/products/p23.jpg", label: "محصول تستی شماره ۲۳" },
  { group: "عکس محصولات", path: "/products/p24.jpg", label: "محصول تستی شماره ۲۴" },
  { group: "عکس محصولات", path: "/products/p25.jpg", label: "محصول تستی شماره ۲۵" },
  { group: "عکس محصولات", path: "/products/p26.jpg", label: "محصول تستی شماره ۲۶" },
  { group: "عکس محصولات", path: "/products/p27.jpg", label: "محصول تستی شماره ۲۷" },
  { group: "عکس محصولات", path: "/products/p28.jpg", label: "محصول تستی شماره ۲۸" },
  { group: "عکس محصولات", path: "/products/p29.jpg", label: "محصول تستی شماره ۲۹" },
  { group: "عکس محصولات", path: "/products/p30.jpg", label: "محصول تستی شماره ۳۰" },
  { group: "عکس محصولات", path: "/products/p31.jpg", label: "محصول تستی شماره ۳۱" },
  { group: "عکس محصولات", path: "/products/p32.jpg", label: "محصول تستی شماره ۳۲" },
  { group: "عکس محصولات", path: "/products/p33.jpg", label: "محصول تستی شماره ۳۳" },
  { group: "عکس محصولات", path: "/products/p34.jpg", label: "محصول تستی شماره ۳۴" },
  { group: "عکس محصولات", path: "/products/p35.jpg", label: "محصول تستی شماره ۳۵" },
  { group: "عکس محصولات", path: "/products/p36.jpg", label: "محصول تستی شماره ۳۶" },
  { group: "عکس محصولات", path: "/products/p37.jpg", label: "محصول تستی شماره ۳۷" },
  { group: "عکس محصولات", path: "/products/p38.jpg", label: "محصول تستی شماره ۳۸" },
  { group: "عکس محصولات", path: "/products/p39.jpg", label: "محصول تستی شماره ۳۹" },
  { group: "عکس محصولات", path: "/products/p40.jpg", label: "محصول تستی شماره ۴۰" },
];
